books/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'books.views',
    url(r'^$', 'book_list', name='book_list'),
    url(r'^list/$', 'books', name='books'),
    url(r'^create-book/$', 'create_book', name='create_book'),
    url(r'^(?P<slug>[-\w]+)/$', 'book_info', name='book_info'),
    url(r'^(?P<slug>[-\w]+)/detail/$', 'view_book', name='view_book'),
    # url(r'^(?P<slug>[-\w]+)/$', 'view_book_doc', name='view_book_doc'),
    url(r'^(?P<slug>[-\w]+)/edit/$', 'edit_book', name='edit_book'),
    url(r'^(?P<slug>[-\w]+)/approve/$', 'approve_book', name='approve_book'),
    url(r'^(?P<slug>[-\w]+)/reject/$', 'reject_book', name='reject_book'),
    url(r'^(?P<slug>[-\w]+)/delete/$', 'delete_book', name='delete_book'),
    url(r'^(?P<slug>[-\w]+)/topics/$', 'view_book_topics', name='view_book_topics'),
    url(r'^(?P<slug>[-\w]+)/create-topic/$', 'create_topic', name='create_topic'),
    url(r'^(?P<book_slug>[-\w]+)/topic/(?P<topic_slug>[-\w]+)/$', 'view_topic', name='view_topic'),
    # url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/edit/$', 'edit_topic', name='edit_topic'),
    url(r'^content/(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', 'create_content', name='create_content'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/reject/$', 'reject_topic', name='reject_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/delete/$', 'delete_topic', name='delete_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/approve/$', 'approve_topic', name='approve_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<subtopic_slug>[-\w]+)/$', 'subtopic_info', name='subtopic_info'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', 'topic_info', name='topic_info'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<subtopic_slug>[-\w]+)/view/$', 'view_subtopic', name='view_subtopic'),
    url(r'^(?P<book_slug>[-\w]+)/change/(?P<topic_slug>[-\w]+)/order/$', 'change_topic_order', name='change_topic_order'),
)

microsite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns(
    '',

    url(r'^$', 'microsite_front.views.index'),
    url(r'^tools/$', 'microsite_front.views.tools', name='tools'),
    url(r'^tools/url-checker/$', 'microsite_front.views.url_checker_tool',
                                                name='url_checker_tool'),
    url(r'^tools/set-meta-data-for-S3-objects/$', 'microsite_front.views.s3_objects_set_metadata',
                                                name='s3_objects_set_metadata'),
    url(r'^report/$', 'micro_blog.views.report'),
    url(r'^contact/$', 'micro_blog.views.contact'),
    url(r'^careers/$', 'microsite_front.views.career_page'),
    url(r'^portal/', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^blog/', include('micro_blog.urls', namespace='micro_blog')),
    url(r'^portal/content/', include('pages.urls', namespace='pages')),
    url(r'^portal/employee/', include('employee.urls', namespace='employee')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^sitemap/$', 'microsite_front.views.html_sitemap'),
    url(r'^(?P<slug>[-\w]+)/$', 'pages.views.site_page'),
    url(r'^rss.xml$', 'microsite_front.xml.rss'),
    url(r'^blog.rss$', 'microsite_front.xml.blog_rss'),
    url(r'^sitemap.xml$', 'microsite_front.xml.sitemap'),
    url(r'^search/autocomplete/$', 'search.views.autocomplete'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^404$', 'micro_blog.views.handler404'),
        url(r'^500$', 'micro_blog.views.handler500'),
    )

books/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.exceptions import ObjectDoesNotExist


STATUS_CHOICES = (
        ('Approved', 'Approved'),
        ('Waiting', 'Waiting'),
        ('Rejected', 'Rejected'),
    )

PRIVACY_CHOICES = (
        ('Private', 'Private'),
        ('Public', 'Public'),
    )


class Book(models.Model):
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='books')
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    updated_on = models.DateTimeField(auto_now_add=True)
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True)
    privacy = models.CharField(max_length=10, choices=PRIVACY_CHOICES)
    keywords = models.CharField(max_length=200, default='')
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __unicode__(self):
        return self.title

    def create_book_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                Book.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

    def save(self, *args, **kwargs):
        title_slug = slugify(self.title)
        if self.id:
            book = Book.objects.get(pk=self.id)
            if book.title != self.title:
                self.slug = self.create_book_slug(title_slug)
        else:
            self.slug = self.create_book_slug(title_slug)

        super(Book, self).save(*args, **kwargs)

    @property
    def owner(self):
        return self.admin.first_name + ' ' + self.admin.last_name


class Topic(models.Model):
    book = models.ForeignKey(Book)
    parent = models.ForeignKey('self', null=True, blank=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    updated_on = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True)

    shadow = models.ForeignKey('self', null=True, blank=True, related_name='versions')
    keywords = models.CharField(max_length=200, default='')
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __unicode__(self):
        return self.title

    def create_topic_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                Topic.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

    def save(self, *args, **kwargs):
        title_slug = slugify(self.title)
        if self.id:
            topic = Topic.objects.get(pk=self.id)
            if topic.title != self.title:
                self.slug = self.create_topic_slug(title_slug)
        else:
            self.slug = self.create_topic_slug(title_slug)

        super(Topic, self).save(*args, **kwargs)


class History(models.Model):
    topic = models.ForeignKey(Topic)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __unicode__(self):
        return self.title

    def create_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                History.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

books/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from books.models import Book, Topic, PRIVACY_CHOICES, History
from books.forms import BookForm, TopicForm
from django.core.exceptions import ObjectDoesNotExist
from micro_admin.models import User
from django.db.models import Q
import json
import datetime


@login_required
def books(request):
    books = Book.objects.all().order_by('created_on')
    return render(request, "docs/books/list_of_books.html", {"books": books})


@login_required
def create_book(request):
    if request.user.is_superuser:
        if request.method == "POST":
            book_form = BookForm(request.POST)

            if book_form.is_valid():
                book = book_form.save()
                book.status = request.POST.get('status') if request.POST.get('status') else 'Waiting'
                book.display_order = Book.objects.all().count()
                book.authors.add(request.user)
                book.save()
                data = {"error": False, "response": "Book created"}

            else:
                data = {"error": True, "response": book_form.errors}

            return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')

        users = User.objects.all()
        return render(request, "docs/books/create_book.html", {"users": users, "privacy_choices": PRIVACY_CHOICES})

    return render_to_response("admin/accessdenied.html")


@login_required
def view_book(request, slug):
    book = get_object_or_404(Book, slug=slug)
    return render(request, "docs/books/book_detail.html", {"book": book})


@login_required
def view_book_topics(request, slug):
    book = get_object_or_404(Book, slug=slug)
    topics = Topic.objects.filter(book=book, parent__isnull=True, shadow__isnull=True)
    return render(request, "docs/topics/list_of_book_topics.html", {"book": book, "topics": topics})


@login_required
def create_topic(request, slug):
    book = get_object_or_404(Book, slug=slug)
    if request.method == "POST":
        topic_form = TopicForm(request.POST)
        
        if topic_form.is_valid():
            topic = topic_form.save()
            topic.status = "Waiting"
            topic.authors.add(request.user)
            
            if request.user not in book.authors.all():
                book.authors.add(request.user)

            if request.POST.get("parent"):
                topic.parent = Topic.objects.get(id=request.POST.get("parent"))

            topic.display_order = Topic.objects.filter(book=book,
                                    parent=topic.parent, shadow__isnull=True).count()
            topic.save()

            data = {"error": False, "response": "Topic created"}
        else:
            data = {"error": True, "response": topic_form.errors}
        
        return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')
    topics = Topic.objects.filter(book=book.id, parent__isnull=True, shadow__isnull=True)    
    return render(request, "docs/topics/create_topic.html", {"book": book, "topics":topics})


@login_required
def create_content(request, book_slug, topic_slug):
    topic = get_object_or_404(Topic, slug=topic_slug)
    book = get_object_or_404(Book, slug=book_slug)
    if request.method == "POST" and request.POST.get("content"):
        if not topic.content:
            topic.content = request.POST.get("content")
            topic.keywords = request.POST.get("keywords")
            topic.updated_on = datetime.datetime.now()
            topic.save()
        else:
            topic_form = TopicForm(request.POST)
        
            if topic_form.is_valid():
                new_topic = topic_form.save()
                new_topic.status = "Waiting"
                new_topic.keywords = request.POST.get("keywords")
                new_topic.authors.add(request.user)

                if request.user not in book.authors.all():
                    book.authors.add(request.user)
                    
                if request.POST.get('parent'):
                    topic_inst = Topic.objects.get(id=request.POST.get('parent'))
                    new_topic.parent = topic_inst

                new_topic.shadow = topic
                new_topic.content = request.POST.get("content")
                new_topic.display_order = Topic.objects.filter(book__slug=book_slug,
                        parent=new_topic.parent, shadow=new_topic.shadow).count()

                new_topic.save()

        if request.user not in topic.authors.all():
            topic.authors.add(request.user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def view_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    topic = get_object_or_404(Topic, slug=topic_slug)
    topic_shadows = Topic.objects.filter(shadow=topic.id)
    return render(request, "docs/topics/topic_detail.html", {"book": book, "topic": topic, "topic_shadows": topic_shadows})


@login_required
def view_subtopic(request, book_slug, topic_slug, subtopic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    topic = get_object_or_404(Topic, slug=topic_slug)
    subtopic = get_object_or_404(Topic, slug=subtopic_slug)
    subtopic_shadows = Topic.objects.filter(shadow=subtopic.id)
    return render(request, "docs/topics/topic_detail.html", {"book": book, "topic": topic, "subtopic": subtopic, "subtopic_shadows": subtopic_shadows})


# @login_required
# def view_book_doc(request, slug):
#     book = Book.objects.get(slug=slug)
#     topics = Topic.objects.filter(book=book, parent__isnull=True, shadow__isnull=True)
#     return render(request, "docs/books/book_document.html", {"book": book, "topics": topics})


@login_required
def edit_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    topic = get_object_or_404(Topic, slug=topic_slug)

    if request.method == "POST":
        topic_form = TopicForm(request.POST)
        
        if topic_form.is_valid():
            new_topic = topic_form.save()
            new_topic.status = "Waiting"
            new_topic.authors.add(request.user)
            
            if request.user not in book.authors.all():
                book.authors.add(request.user)

            if request.user not in topic.authors.all():
                topic.authors.add(request.user)

            if request.POST.get('parent'):
                new_topic.parent = request.POST.get('parent')

            new_topic.shadow = topic

            new_topic.save()

            data = {"error": False, "response": "Topic has been edited Successfully"}
        else:
            data = {"error": True, "response": topic_form.errors}
        
        return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')
    topics = Topic.objects.filter(book=book.id, parent__isnull=True, shadow__isnull=True)    
    return render(request, "docs/topics/edit_topic.html", {"book": book, "topics":topics, "topic": topic})


@login_required
def approve_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    
    if request.user.is_superuser or book.admin == request.user:
        
        topic = get_object_or_404(Topic, slug=topic_slug)
        if topic.shadow:
            history = History.objects.create(topic=topic.shadow, title=topic.shadow.title, 
                            content=topic.shadow.content)

            history.slug = history.create_slug(topic.shadow.slug)
            history.save()

            topic.shadow.title = topic.title
            topic.shadow.status = "Approved"
            topic.shadow.content = topic.content
            topic.shadow.keywords = topic.keywords
            topic.shadow.updated_on = datetime.datetime.now()
            topic.shadow.save()

            topic.delete()
            data = {"topic_slug": topic.shadow.slug, "response": "Approved Successfully"}
        else:
            topic.status = "Approved"
            topic.save()
            data = {"response": "Approved Successfully"}
    else:
        data = {"response": "You don't have the permission to Approve."}
    return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')


@login_required
def reject_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    
    if request.user.is_superuser or book.admin == request.user:
        topic = get_object_or_404(Topic, slug=topic_slug)
        topic.status = "Rejected"
        topic.save()
        data = {"response": "Rejected Successfully"}
    else:
        data = {"response": "You don't have the permission to Reject."}
    return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')


@login_required
def delete_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    
    if request.user.is_superuser or book.admin == request.user:
        topic = get_object_or_404(Topic, slug=topic_slug)
        topic_id = topic.id
        topic.delete()

        if not topic.shadow:
            remaining_topics = Topic.objects.filter(id__gte=topic_id, parent=topic.parent, shadow=topic.shadow)
            for each_topic in remaining_topics:
                each_topic.display_order = (each_topic.display_order) - 1
                each_topic.save()

        data = {"response": "Deleted Successfully"}
    else:
        data = {"response": "You don't have the permission to Delete."}
    return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')


@login_required
def edit_book(request, slug):
    book = get_object_or_404(Book, slug=slug)
    if request.user.is_superuser or book.admin == request.user:

        if request.method == "POST":

templates/docs/books/book_detail.html
{% extends 'admin/base.html' %} 
{% load user_tags %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="/portal/">Home</a></li>
  <li><a href="/books/list/">Books</a></li>
  <li class="active">Book Details</li>
</ol>
{% endblock breadcrumb %}
{% block stage %}
<div class="panel panel-default blog-list">
    <div class="panel-heading">
      <h3 class="panel-title">Book Detail Page</h3>
      <span>
        <a href="{% url 'books:create_topic' slug=book.slug %}?topic='parent-topic'&topic_id=''"><button class="btn btn-warning"><i class='fa fa-plus'></i> Add New Topic </button></a>
        <a href="{% url 'books:view_book_topics' slug=book.slug %}"><button class="btn btn-warning">View Topics </button></a>
        <a href="{% url 'books:book_info' slug=book.slug %}"><button class="btn btn-warning">Preview</button></a>
      </span>
    </div>
    <div class="panel-body">
      <div class="blog-left">
        <!--book content-->
        <!--row-->
        <div class="row marl title_row">
          <span class="book_admin">Book Admin : </span><span class="admin_name">{{book.owner}}</span>
          <span class="created_on">Created On : </span><span class="created_detail">{{book.created_on}}</span>
          <span class="updated_on">Updated On : </span><span class="created_detail">{{book.updated_on}}</span>
          <span class="actions_book">
            <a href="{% url 'books:edit_book' slug=book.slug %}" title="Edit Book"><i class="fa fa-pencil-square-o"></i></a>
            <a href="{% url 'books:approve_book' slug=book.slug %}" title="Approve Book"><i class="fa fa-check"></i></a>
            <a href="{% url 'books:reject_book' slug=book.slug %}" title="Reject Book"><i class="fa fa-times"></i></a>
            <a href="{% url 'books:delete_book' slug=book.slug %}" title="Delete Book"><i class="fa fa-trash-o"></i></a>
          </span>
          <div class="slug_div">
            <span class="slug">Slug : </span><span>{{book.slug}}</span>
            <span class="status">Status : </span><span>{{book.status}}</span>
          </div>
        </div>
        <!--TITLE AND DESCRIPTON-->
        <div class="row marl book_detail authors_div">
          <!--<span class="image_cover_page">
          <img src="isla-and-the-happily-ever-after-196x300.jpg">
          </span>-->
          <span class="book_title">{{book.title|capfirst}}</span><span class="authors" style="background-color:#FFEFC6;">{{ book.privacy }}</span>
          <div class="description_div">
            <span>Description :</span>
            {{book.description|convert_to_html|safe}}
          </div>
          <div class="description_div">
            <span>Keywords :</span>
            {{book.keywords}}
          </div>
        </div>
        <!--/TITLE AND DESCRIPTION-->
        <!--AUTHORS ROW-->
        <div class="row marl authors_div">
          <span class="authors">Authors</span>
            {% for author in book.authors.all %}
              <span class="{% if forloop.counter > 1 %}author_name{% endif %}">{{author.get_full_name}}</span>
            {% endfor %}
        </div>
        <!--/AUTHORS ROW-->
        <!--ROW-->
        <!--/book content-->
      </div>
    </div>
</div>
{% endblock %}
<!-- main content ends here-->

templates/docs/books/create_book.html
{% extends 'admin/base.html' %} 

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="/portal/">Home</a></li>
  <li><a href="/books/list/">Books</a></li>
  <li class="active">Create Book</li>
</ol>
{% endblock breadcrumb %}
{% block stage %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Book Creation</h3>
  </div>
  <div class="panel-body">
    <form action="." method="POST" id="book_form">
      {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputEmail1">Title <span>*</span></label>
        <input type="Text" class="form-control" id="title" name="title">
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Book Admin <span>*</span></label>
        <select name="admin" id="admin" style="color:black;">
          <option value="select">Select Book Admin</option>
          {% for user in users %}
            <option value="{{user.id}}">{% if user.get_full_name %}{{ user.get_full_name }} {% else %} {{user.email}} {% endif %} </option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Privacy Setting <span>*</span> : </label>
        <div id="privacy" style="display:inline-block">
          {% for privacy_choice in privacy_choices %}
            <input type="radio" class="pagination" name="privacy" value="{{ privacy_choice.0 }}">{{ privacy_choice.0 }}
          {% endfor %}
        </div>
      </div>
      <div class="form-group">
        <label class="control-label" for="html">Description <span>*</span></label>
        <div class="control-group">
          <div class="controls" id="content">
            <textarea class="form-control" name="description" rows="10" cols="100" placeholder="Write the description here" id="description"></textarea>
            {# <input type="hidden" name="description" id="description"> #}
          </div>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label" for="html">Keywords <span>*</span></label>
        <div class="control-group">
          <div class="controls" id="content">
            <textarea class="form-control" name="keywords" rows="3" cols="100" placeholder="Write the meta tag keywords here" id="keywords"></textarea>
          </div>
        </div>
      </div>
      <div>
        <input type="radio" class="pagination" name="status" value="Waiting"> Waiting<br/>
        <input type="radio" class="pagination" name="status" value="Approved"> Approve
      </div>
      <div class="save-btn">
        <i class="fa fa-floppy-o"></i><input type="submit" value="Save" class="save" id="search_lessons">
      </div>
    </form>
  </div>
</div>
{% load compress %}
{% compress js %}
<script type="text/javascript">
  $ = jQuery;
    $('form#book_form').ajaxForm({
      type:'POST',
      dataType: 'json',
      data:$('#book_form').serialize(),
      success: function(data) {
        if (data.error) {
          $('p.failure').remove();
          for (var key in data.response) {
            $('#' + key).after('<p class="failure">' + data.response[key] + '</p>');
          }
        } else {
          window.location = "{% url 'books:books' %}";
        }
      }
    });
</script>
{% endcompress %}
{% endblock %}

templates/docs/books/list_of_books.html
{% extends 'admin/base.html' %} 

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="/portal/">Home</a></li>
  <li class="active">Books</li>
</ol>
{% endblock breadcrumb %}
{% block stage %}
<!-- main content starts here-->
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Book Viewer</h3>
    <span>
      <span class='active_user'><i class="fa fa-square"></i>Approved</span>
      <span class='inactive_user'><i class="fa fa-square"></i>Waiting/Rejected</span>
      {% if request.user.is_superuser %}
        <a href="{% url 'books:create_book' %}"><button class="btn btn-warning"><i class='fa fa-plus'></i> Add New Book </button></a>
      {% endif %}
    </span>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped" id="books_list">
        <thead>
          <tr>
            <th width='1%'>No</th>
            <th width="8%">Title</th>
            <th width="8%">Slug</th>
            <th width="3%">Privacy</th>
            <th width="10%">Owner</th>
            <th width="13%">Created Date</th>
            <th width="15%">Authors</th>
            <th width="25%">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for book in books %}
          <tr class="{% ifequal book.status 'Approved' %}success{% else %}danger{% endifequal %}">
            <td>{{forloop.counter}}</td>
            <td><a href="{% url 'books:view_book' slug=book.slug %}">{{book.title}}</a></td>
            <td>{{book.slug}}</td>
            <td>{{book.privacy}}</td>
            <td>{{book.owner}}</td>
            <td>{{book.created_on}}</td>
            <td class="authors_div">{% for author in book.authors.all %}
              <span class="{% if forloop.counter > 1 %}author_name{% endif %}">{{author.get_full_name}}</span>
            {% endfor %}</td>
            <td>
              <a href="{% url 'books:edit_book' slug=book.slug %}" class="edit_anchor"><i class="fa fa-pencil-square-o"></i>Edit</a>
              <a href="{% url 'books:delete_book' slug=book.slug %}" class="delete_anchor"><i class="fa fa-trash-o trash-color"></i>Delete</a>
              <a href="{% url 'books:book_info' slug=book.slug %}" title="Preview Topic" class="preview-btn-click edit_anchor"><i class="fa fa-eye" style="padding-right:1px;"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% load compress %}
{% compress js %}
<script type="text/javascript">
  $ = jQuery;
  $(document).ready(function() {

    $('#books_list').DataTable({
      "sPaginationType": "full_numbers",
      "bSort": false 
    });

  });
</script>>
{% endcompress %}
<!-- main content ends here-->
{% endblock %}