books/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'books.views',
    url(r'^$', 'book_list', name='book_list'),
    url(r'^list/$', 'books', name='books'),
    url(r'^create-book/$', 'create_book', name='create_book'),
    url(r'^(?P<slug>[-\w]+)/$', 'book_info', name='book_info'),
    url(r'^(?P<slug>[-\w]+)/detail/$', 'view_book', name='view_book'),
    # url(r'^(?P<slug>[-\w]+)/$', 'view_book_doc', name='view_book_doc'),
    url(r'^(?P<slug>[-\w]+)/edit/$', 'edit_book', name='edit_book'),
    url(r'^(?P<slug>[-\w]+)/approve/$', 'approve_book', name='approve_book'),
    url(r'^(?P<slug>[-\w]+)/reject/$', 'reject_book', name='reject_book'),
    url(r'^(?P<slug>[-\w]+)/delete/$', 'delete_book', name='delete_book'),
    url(r'^(?P<slug>[-\w]+)/topics/$', 'view_book_topics', name='view_book_topics'),
    url(r'^(?P<slug>[-\w]+)/create-topic/$', 'create_topic', name='create_topic'),
    url(r'^(?P<book_slug>[-\w]+)/topic/(?P<topic_slug>[-\w]+)/$', 'view_topic', name='view_topic'),
    # url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/edit/$', 'edit_topic', name='edit_topic'),
    url(r'^content/(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', 'create_content', name='create_content'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/reject/$', 'reject_topic', name='reject_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/delete/$', 'delete_topic', name='delete_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/approve/$', 'approve_topic', name='approve_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<subtopic_slug>[-\w]+)/$', 'subtopic_info', name='subtopic_info'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', 'topic_info', name='topic_info'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<subtopic_slug>[-\w]+)/view/$', 'view_subtopic', name='view_subtopic'),
    url(r'^(?P<book_slug>[-\w]+)/change/(?P<topic_slug>[-\w]+)/order/$', 'change_topic_order', name='change_topic_order'),
)

microsite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns(
    '',

    url(r'^$', 'microsite_front.views.index'),
    url(r'^tools/$', 'microsite_front.views.tools', name='tools'),
    url(r'^tools/url-checker/$', 'microsite_front.views.url_checker_tool',
                                                name='url_checker_tool'),
    url(r'^tools/set-meta-data-for-S3-objects/$', 'microsite_front.views.s3_objects_set_metadata',
                                                name='s3_objects_set_metadata'),
    url(r'^report/$', 'micro_blog.views.report'),
    url(r'^contact/$', 'micro_blog.views.contact'),
    url(r'^careers/$', 'microsite_front.views.career_page'),
    url(r'^portal/', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^blog/', include('micro_blog.urls', namespace='micro_blog')),
    url(r'^portal/content/', include('pages.urls', namespace='pages')),
    url(r'^portal/employee/', include('employee.urls', namespace='employee')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^sitemap/$', 'microsite_front.views.html_sitemap'),
    url(r'^(?P<slug>[-\w]+)/$', 'pages.views.site_page'),
    url(r'^rss.xml$', 'microsite_front.xml.rss'),
    url(r'^blog.rss$', 'microsite_front.xml.blog_rss'),
    url(r'^sitemap.xml$', 'microsite_front.xml.sitemap'),
    url(r'^search/autocomplete/$', 'search.views.autocomplete'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^404$', 'micro_blog.views.handler404'),
        url(r'^500$', 'micro_blog.views.handler500'),
    )

books/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.exceptions import ObjectDoesNotExist


STATUS_CHOICES = (
        ('Approved', 'Approved'),
        ('Waiting', 'Waiting'),
        ('Rejected', 'Rejected'),
    )

PRIVACY_CHOICES = (
        ('Private', 'Private'),
        ('Public', 'Public'),
    )


class Book(models.Model):
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='books')
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    updated_on = models.DateTimeField(auto_now_add=True)
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True)
    privacy = models.CharField(max_length=10, choices=PRIVACY_CHOICES)
    keywords = models.CharField(max_length=200, default='')
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __unicode__(self):
        return self.title

    def create_book_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                Book.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

    def save(self, *args, **kwargs):
        title_slug = slugify(self.title)
        if self.id:
            book = Book.objects.get(pk=self.id)
            if book.title != self.title:
                self.slug = self.create_book_slug(title_slug)
        else:
            self.slug = self.create_book_slug(title_slug)

        super(Book, self).save(*args, **kwargs)

    @property
    def owner(self):
        return self.admin.first_name + ' ' + self.admin.last_name


class Topic(models.Model):
    book = models.ForeignKey(Book)
    parent = models.ForeignKey('self', null=True, blank=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    updated_on = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True)

    shadow = models.ForeignKey('self', null=True, blank=True, related_name='versions')
    keywords = models.CharField(max_length=200, default='')
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __unicode__(self):
        return self.title

    def create_topic_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                Topic.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

    def save(self, *args, **kwargs):
        title_slug = slugify(self.title)
        if self.id:
            topic = Topic.objects.get(pk=self.id)
            if topic.title != self.title:
                self.slug = self.create_topic_slug(title_slug)
        else:
            self.slug = self.create_topic_slug(title_slug)

        super(Topic, self).save(*args, **kwargs)


class History(models.Model):
    topic = models.ForeignKey(Topic)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __unicode__(self):
        return self.title

    def create_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                History.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

templates/docs/topics/create_topic.html
{% extends 'admin/base.html' %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="/portal/">Home</a></li>
  <li><a href="/books/list/">Books</a></li>
  <li><a href="/books/{{book.slug}}/detail/">{{book.slug}}</a></li>
  <li class="active">Create Topic</li>
</ol>
{% endblock breadcrumb %} 
{% block stage %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Topic Creation</h3>
  </div>
  <div class="panel-body">
    <form action="." method="POST" id="topic_form">
      {% csrf_token %}
      <input type="hidden" name="book" value="{{book.id}}">
      <div class="form-group">
        <label for="exampleInputEmail1">Parent <span>*</span></label>
        <select id="parent" name="parent" class="form-control">
          <option value="">Top Level</option>
          {% for topic in topics %}
          <option value="{{topic.id}}">{{topic.title}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Title <span>*</span></label>
        <input type="Text" class="form-control" id="title" name="title">
      </div>
      <div class="save-btn">
        <i class="fa fa-floppy-o"></i><input type="submit" value="Save" class="save" id="search_lessons">
      </div>
    </form>
  </div>
</div>
<!-- main content ends here-->
{% load compress %}
{% compress js %}
<script type="text/javascript">
  $ = jQuery;
    $('form#topic_form').ajaxForm({
      type:'POST',
      dataType: 'json',
      data:$('#topic_form').serialize(),
      success: function(data) {
        if (data.error) {
          $('p.failure').remove();
          for (var key in data.response) {
            $('#' + key).after('<p class="failure">' + data.response[key] + '</p>');
          }
        } else {
          window.location = "{% url 'books:view_book_topics' slug=book.slug %}";
        }
      }
    });
</script>
{% endcompress %}
{% endblock %}

templates/docs/topics/list_of_book_topics.html
{% extends 'admin/base.html' %}
{% load user_tags %}
{% load topics_filters %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="/portal/">Home</a></li>
  <li><a href="/books/list/">Books</a></li>
  <li><a href="/books/{{book.slug}}/detail/">{{book.slug}}</a></li>
  <li class="active">Topics</li>
</ol>
{% endblock breadcrumb %}
{% block stage %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{book.title|capfirst}} - Topics List</h3>
    <span>
      <span class='active_user'><i class="fa fa-square"></i>Approved</span>
      <span class='inactive_user'><i class="fa fa-square"></i>Waiting/Rejected</span>
      <a href="{% url 'books:create_topic' slug=book.slug %}?topic='parent-topic'&topic_id=''"><button class="btn btn-warning">Add New Topic</button></a>
    </span>
  </div>
  <div class="panel-body topic_list_div">
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th width="10%">Title</th>
            <th width="10%">Slug</th>
            <th width="6%">Status</th>
            <th width="5%">Swap</th>
            <th width="15%">Authors</th>
            <th width="10%">Created Date</th>
            <th width="10%">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for topic in topics %}
            {% with sub_topics=topic|get_sub_topics %}
              <tr class="parent_row {% ifequal topic.status 'Approved' %}success{% else %}danger{% endifequal %}">
                <td><a href="{% url 'books:view_topic' book_slug=book.slug topic_slug=topic.slug %}">{{topic.title}}</a></td>
                <td>{{topic.slug}}</td>
                <td>{{topic.status}}</td>
                <td class="menu-swap txt_center">
                  <div class="inner-swap-wid txt_center">
                    <span class="caret-wid"><a href="#"><i class="fa fa-caret-down" 
                      post-url="{% url 'books:change_topic_order' book_slug=book.slug topic_slug=topic.slug %}"></i></a></span>
                    <span class="caret-wid"><a href="#"><i class="fa fa-caret-up" 
                      post-url="{% url 'books:change_topic_order' book_slug=book.slug topic_slug=topic.slug %}"></i></a></span>
                  </div>
                </td>
                <td class="authors_div">{% for author in topic.authors.all %}
                  <span class="{% if forloop.counter > 1 %}author_name{% endif %}">{{author.get_full_name}}</span>
                {% endfor %}</td>
                <td>{{topic.created_on}}</td>
                <td>
                  <a href="{% url 'books:delete_topic' book_slug=book.slug topic_slug=topic.slug %}" title="Delete Topic" class="delete-btn-click delete_anchor"><i class="fa fa-trash-o trash-color"></i>Delete</a>
                  {% if topic.status == "Waiting" or topic.status == "Rejected" %}
                  <a href="{% url 'books:approve_topic' book_slug=book.slug topic_slug=topic.slug %}" title="Approve" class="delete-btn-click check_anchor"><i class="fa fa-check check-color"></i></a>
                  {% endif %}
                  {% if topic.status == "Waiting" or topic.status == "Approved" %}
                  <a href="{% url 'books:reject_topic' book_slug=book.slug topic_slug=topic.slug %}" title="Reject" class="delete-btn-click cross_anchor"><i class="fa fa-times remove-color"></i></a>
                  {% endif %}
                  <a href="{% url 'books:topic_info' book_slug=book.slug topic_slug=topic.slug %}" title="Preview Topic" class="preview-btn-click edit_anchor"><i class="fa fa-eye" style="padding-right:1px;"></i></a>
                </td>
              </tr>
              {% if sub_topics %}
                {% for subtopic in sub_topics %}
                  <tr class="subtopic-of-{{topic.id}} {% ifequal subtopic.status 'Approved' %}success{% else %}danger{% endifequal %}">
                    <td class="sub-topic-title">{{subtopic.title}}</td>
                    <td>{{subtopic.slug}}</td>
                    <td>{{subtopic.status}}</td>
                    <td class="menu-swap txt_center">
                      <div class="inner-swap-wid txt_center">
                        <span class="caret-wid"><a href="#"><i class="fa fa-caret-down" 
                          post-url="{% url 'books:change_topic_order' book_slug=book.slug topic_slug=subtopic.slug %}"></i></a></span>
                        <span class="caret-wid"><a href="#"><i class="fa fa-caret-up" 
                          post-url="{% url 'books:change_topic_order' book_slug=book.slug topic_slug=subtopic.slug %}"></i></a></span>
                      </div>
                    </td>
                    <td class="authors_div">{% for author in subtopic.authors.all %}
                      <span class="{% if forloop.counter > 1 %}author_name{% endif %}">{{author.get_full_name}}</span>
                    {% endfor %}</td>
                    <td>{{subtopic.created_on}}</td>
                    <td>
                      <a href="{% url 'books:delete_topic' book_slug=book.slug topic_slug=subtopic.slug %}" title="Delete Sub Topic" class="delete-btn-click delete_anchor"><i class="fa fa-trash-o"></i>Delete</a>
                      {% if subtopic.status == "Waiting" or subtopic.status == "Rejected" %}
                      <a href="{% url 'books:approve_topic' book_slug=book.slug topic_slug=subtopic.slug %}" title="Approve" class="delete-btn-click check_anchor"><i class="fa fa-check check-color"></i></a>
                      {% endif %}
                      {% if subtopic.status == "Waiting" or subtopic.status == "Approved" %}
                      <a href="{% url 'books:reject_topic' book_slug=book.slug topic_slug=subtopic.slug %}" title="Reject" class="delete-btn-click cross_anchor"><i class="fa fa-times remove-color"></i></a>
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
              {% endif %}
            {% endwith %}
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- main content ends here-->
{% load compress %}
{% compress js %}
<script type="text/javascript">
  $('.delete-btn-click').click(function(e) {
    e.preventDefault();
    $.post($(this).attr('href'), {'title': $(this).attr('title')}, function(data){
        alert(data.response);
        window.location = '.';
      }, "json");
  });
  $(document).ready(function() {
    $('.fa-caret-down').click(function(){
        $.post(($(this).attr('post-url')),{'mode':'down'},function(data){
          if (data.message){
            alert(data.message);
          }
          window.location = '.';
        }, 'json');
    });
    $('.fa-caret-up').click(function(){
        $.post(($(this).attr('post-url')),{'mode':'up'},function(data){
          if (data.message){
            alert(data.message);
          }
          window.location = '.';
        }, 'json');
    });
  });
</script>
{% endcompress %}
{% endblock %}

templates/docs/topics/topic_detail.html
{% extends 'admin/base.html' %}
{% load user_tags %}
{% load topics_filters %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="/portal/">Home</a></li>
  <li><a href="/books/list/">Books</a></li>
  <li><a href="/books/{{book.slug}}/detail/">{{book.slug}}</a></li>
  <li><a href="/books/{{book.slug}}/topics/">Topics</a></li>
  <li class="active">Topic Details</li>
</ol>
{% endblock breadcrumb %}
{% block stage %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Topic Detail</h3>
  </div>
  <div class="panel-body">
    <div class="col-md-3 tree_div">
      <ul class="parent_list">
        <li class="topic li_active"><a href="{% url 'books:view_topic' topic_slug=topic.slug book_slug=book.slug %}"><i class="fa fa-caret-right"></i>{{topic.title|capfirst}}</a>
          <ul class="sub_topic_list">
            {% for subtopic in topic.topic_set.all %}
              {% if not subtopic.shadow %}
              <li class="sub-topic"><a href="{% url 'books:view_subtopic' subtopic_slug=subtopic.slug topic_slug=topic.slug book_slug=book.slug %}"><i class="fa fa-file-text-o"></i>{{subtopic.title|capfirst}}</a></li>
              {% endif %}
            {% endfor %}
          </ul>
        </li>
      </ul>
    </div>
    <div class="col-md-9 content_div">
    <div>
    {% if topic_shadows %}
    <span>Shadows:</span>
      <p>{% for shadow in topic_shadows %}
      <a href="{% url 'books:view_topic' topic_slug=shadow.slug book_slug=book.slug %}"><span>Shadow {{forloop.counter}}</span></a>
      {% endfor %}</p>
    {% endif %}
    {% if subtopic_shadows %}
    <span>Shadows:</span>
      <p>{% for shadow in subtopic_shadows %}
      <a href="{% url 'books:view_subtopic' subtopic_slug=shadow.slug topic_slug=topic.slug book_slug=book.slug %}"><span>Shadow {{forloop.counter}}</span></a>
      {% endfor %}</p>
    {% endif %}
    <!-- Start of Topic History list -->
    {% if topic and not subtopic %}
      {% if topic.history_set.count %}
        <a class="view_history"><span>View History</span></a>
        <div id="history_div">
          {% for history in topic.history_set.all %}
            <a pan-id="#version-{{history.id}}" class="view_version"><span>Version {{forloop.counter}}</span></a>
          {% endfor %}
        </div>
      {% endif %}
    {% endif %}
    <!-- End of Topic History list -->

    <!-- Start of Sub Topic History list -->
    {% if subtopic %}
      {% if subtopic.history_set.count %}
        <a class="view_history"><span>View History</span></a>
        <div id="history_div">
          {% for history in subtopic.history_set.all %}
            <a pan-id="#version-{{history.id}}" class="view_version"><span>Version {{forloop.counter}}</span></a>
          {% endfor %}
        </div>
      {% endif %}
    {% endif %}
    <!-- End of Sub Topic History list -->

    </div>
    <!-- Start of Topic History View -->
    {% if topic and not subtopic%}
      <div>
        {% for history in topic.history_set.all %}
          <div id="version-{{history.id}}" class="versions_div">
            <h5>{{history.title|capfirst}} - on {{history.date}}</h5>
            Content: {{history.content}}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <!-- End of Topic History View -->

    <!-- Start of Sub Topic History View -->
    {% if subtopic%}
      <div>
        {% for history in subtopic.history_set.all %}
          <div id="version-{{history.id}}" class="versions_div">
            <h5>{{history.title|capfirst}} - on {{history.date}}</h5>
            Content: {{history.content}}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <!-- End of Sub Topic History View -->

      <div class="topics_div">
      {% if topic and not subtopic%}
        <h5>{{topic.title|capfirst}}</h5>
        <p>
          {% if topic.status == "Approved" %}
            Approved
          {% else %}
            Waiting for Approval
          {% endif %}
          </p>
        <div class="row marl">
        <span class="actions_book">
        {% if topic.status == "Waiting" or topic.status == "Rejected" %}  
          <a href="{% url 'books:approve_topic' book_slug=book.slug topic_slug=topic.slug %}" title="Approve Topic" class="btn-click"><i class="fa fa-check"></i></a>
        {% endif %}
        {% if topic.status == "Waiting" or topic.status == "Approved" %}  
          <a href="{% url 'books:reject_topic' book_slug=book.slug topic_slug=topic.slug %}" title="Reject Topic" class="btn-click"><i class="fa fa-times"></i></a>
        {% endif %}  
          <a href="{% url 'books:delete_topic' book_slug=book.slug topic_slug=topic.slug %}" title="Delete Topic" class="delete-btn-click"><i class="fa fa-trash-o"></i></a>
          <a href="{% url 'books:topic_info' book_slug=book.slug topic_slug=topic.slug %}" title="preview Topic" class="preview-btn-click"><i class="fa fa-eye"></i></a>
        </span>
        </div>
        <div class="row marl">
        <form action="{% url "books:create_content" topic_slug=topic.slug book_slug=book.slug %}" method="post">
          <input type="hidden" name="book" value="{{book.id}}">
          <input type="hidden" name="topic" value="{{topic}}">
          <input type="hidden" name="title" value="{{topic.title}}">
          <input type="hidden" name="parent" value="{{topic.parent.id}}">
          Content: <textarea name="content" class="form-control" rows="10" cols="50">{{ topic.content }}</textarea><br />
          Keywords: <textarea name="keywords" class="form-control" rows="2" cols="50"required="True">{{ topic.keywords }}</textarea><br />
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>  
        </div>
        {% endif %}
        {% if subtopic %}
          <h5>{{subtopic.title|capfirst}}</h5>
          <p>
          {% if subtopic.status == "Approved" %}
            Approved
          {% else %}
            Waiting for Approval
          {% endif %}
          </p>
          <div class="row marl">
          <span class="actions_book">
          {% if subtopic.status == "Waiting" or subtopic.status == "Rejected" %}
            <a href="{% url 'books:approve_topic' book_slug=book.slug topic_slug=subtopic.slug %}" title="Approve Sub Topic" class="btn-click"><i class="fa fa-check"></i></a>
          {% endif %}
          {% if subtopic.status == "Waiting" or subtopic.status == "Approved" %}  
            <a href="{% url 'books:reject_topic' book_slug=book.slug topic_slug=subtopic.slug %}" title="Reject Sub Topic" class="btn-click"><i class="fa fa-times"></i></a>
          {% endif %}
            <a href="{% url 'books:delete_topic' book_slug=book.slug topic_slug=subtopic.slug %}" title="Delete Sub Topic" class="delete-btn-click"><i class="fa fa-trash-o"></i></a>
          </span>
         </div> 
        <div class="row marl">
        <form action="{% url "books:create_content" topic_slug=subtopic.slug book_slug=book.slug %}" method="post">
          <input type="hidden" name="book" value="{{book.id}}">
          <input type="hidden" name="topic" value="{{subtopic}}">
          <input type="hidden" name="title" value="{{subtopic.title}}">
          <input type="hidden" name="parent" value="{{subtopic.parent.id}}">
          Content: <textarea name="content" class="form-control" rows="10" cols="50">{{ subtopic.content }}</textarea><br />
          Keywords: <textarea name="keywords" class="form-control" rows="2" cols="50" required="True">{{ subtopic.keywords }}</textarea><br />
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>  
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% load compress %}
{% compress js %}
<script type="text/javascript">

  $(document).ready(function() {

    if($('a[href="'+window.location.pathname+'"]').parent('li').hasClass("topic")){
      
      $('a[href="'+window.location.pathname+'"]').parent('li').children('ul').slideDown('slow');

      $('a[href="'+window.location.pathname+'"]').children('i').css({
        "transform":"rotate(90deg)",
        "padding-left":"9px",
      });
    }

    if($('a[href="'+window.location.pathname+'"]').parent('li').hasClass("sub-topic")){
      
      $('a[href="'+window.location.pathname+'"]').parent('li').parent('ul').slideDown('slow');

      $('a[href="'+window.location.pathname+'"]').parent('li').parent('ul').parent('li').children('a').children('i').css({
        "transform":"rotate(90deg)",
        "padding-left":"9px",
      });
    }

    $("#history_div").hide();
    $(".versions_div").hide();

    $(".view_history").click(function(e) {
      $("#history_div").show();
    });

    $(".view_version").click(function(e) {
      $(".versions_div").hide();
      $(".topics_div").hide();
      $($(this).attr("pan-id")).show();
    });

    $('.btn-click').click(function(e) {
      e.preventDefault();
      $.post($(this).attr('href'), {'title': $(this).attr('title')}, function(data){
          alert(data.response);
          if(data.topic_slug){
            window.location = '/books/{{book.slug}}/topic/'+ data.topic_slug;
          }
        }, "json");
    });

    $('.delete-btn-click').click(function(e) {
      e.preventDefault();
      $.post($(this).attr('href'), {'title': $(this).attr('title')}, function(data){
          alert(data.response);
          window.location = '.';
        }, "json");
    });
    
  });

</script>
{% endcompress %}
{% endblock %}