books/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'books.views',
    url(r'^$', 'book_list', name='book_list'),
    url(r'^list/$', 'books', name='books'),
    url(r'^create-book/$', 'create_book', name='create_book'),
    url(r'^(?P<slug>[-\w]+)/$', 'book_info', name='book_info'),
    url(r'^(?P<slug>[-\w]+)/detail/$', 'view_book', name='view_book'),
    # url(r'^(?P<slug>[-\w]+)/$', 'view_book_doc', name='view_book_doc'),
    url(r'^(?P<slug>[-\w]+)/edit/$', 'edit_book', name='edit_book'),
    url(r'^(?P<slug>[-\w]+)/approve/$', 'approve_book', name='approve_book'),
    url(r'^(?P<slug>[-\w]+)/reject/$', 'reject_book', name='reject_book'),
    url(r'^(?P<slug>[-\w]+)/delete/$', 'delete_book', name='delete_book'),
    url(r'^(?P<slug>[-\w]+)/topics/$', 'view_book_topics', name='view_book_topics'),
    url(r'^(?P<slug>[-\w]+)/create-topic/$', 'create_topic', name='create_topic'),
    url(r'^(?P<book_slug>[-\w]+)/topic/(?P<topic_slug>[-\w]+)/$', 'view_topic', name='view_topic'),
    # url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/edit/$', 'edit_topic', name='edit_topic'),
    url(r'^content/(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', 'create_content', name='create_content'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/reject/$', 'reject_topic', name='reject_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/delete/$', 'delete_topic', name='delete_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/approve/$', 'approve_topic', name='approve_topic'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<subtopic_slug>[-\w]+)/$', 'subtopic_info', name='subtopic_info'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', 'topic_info', name='topic_info'),
    url(r'^(?P<book_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<subtopic_slug>[-\w]+)/view/$', 'view_subtopic', name='view_subtopic'),
    url(r'^(?P<book_slug>[-\w]+)/change/(?P<topic_slug>[-\w]+)/order/$', 'change_topic_order', name='change_topic_order'),
)

microsite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns(
    '',

    url(r'^$', 'microsite_front.views.index'),
    url(r'^tools/$', 'microsite_front.views.tools', name='tools'),
    url(r'^tools/url-checker/$', 'microsite_front.views.url_checker_tool',
                                                name='url_checker_tool'),
    url(r'^tools/set-meta-data-for-S3-objects/$', 'microsite_front.views.s3_objects_set_metadata',
                                                name='s3_objects_set_metadata'),
    url(r'^report/$', 'micro_blog.views.report'),
    url(r'^contact/$', 'micro_blog.views.contact'),
    url(r'^careers/$', 'microsite_front.views.career_page'),
    url(r'^portal/', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^blog/', include('micro_blog.urls', namespace='micro_blog')),
    url(r'^portal/content/', include('pages.urls', namespace='pages')),
    url(r'^portal/employee/', include('employee.urls', namespace='employee')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^sitemap/$', 'microsite_front.views.html_sitemap'),
    url(r'^(?P<slug>[-\w]+)/$', 'pages.views.site_page'),
    url(r'^rss.xml$', 'microsite_front.xml.rss'),
    url(r'^blog.rss$', 'microsite_front.xml.blog_rss'),
    url(r'^sitemap.xml$', 'microsite_front.xml.sitemap'),
    url(r'^search/autocomplete/$', 'search.views.autocomplete'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^404$', 'micro_blog.views.handler404'),
        url(r'^500$', 'micro_blog.views.handler500'),
    )

books/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.exceptions import ObjectDoesNotExist


STATUS_CHOICES = (
        ('Approved', 'Approved'),
        ('Waiting', 'Waiting'),
        ('Rejected', 'Rejected'),
    )

PRIVACY_CHOICES = (
        ('Private', 'Private'),
        ('Public', 'Public'),
    )


class Book(models.Model):
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='books')
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    updated_on = models.DateTimeField(auto_now_add=True)
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True)
    privacy = models.CharField(max_length=10, choices=PRIVACY_CHOICES)
    keywords = models.CharField(max_length=200, default='')
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __unicode__(self):
        return self.title

    def create_book_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                Book.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

    def save(self, *args, **kwargs):
        title_slug = slugify(self.title)
        if self.id:
            book = Book.objects.get(pk=self.id)
            if book.title != self.title:
                self.slug = self.create_book_slug(title_slug)
        else:
            self.slug = self.create_book_slug(title_slug)

        super(Book, self).save(*args, **kwargs)

    @property
    def owner(self):
        return self.admin.first_name + ' ' + self.admin.last_name


class Topic(models.Model):
    book = models.ForeignKey(Book)
    parent = models.ForeignKey('self', null=True, blank=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    updated_on = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=True)

    shadow = models.ForeignKey('self', null=True, blank=True, related_name='versions')
    keywords = models.CharField(max_length=200, default='')
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __unicode__(self):
        return self.title

    def create_topic_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                Topic.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

    def save(self, *args, **kwargs):
        title_slug = slugify(self.title)
        if self.id:
            topic = Topic.objects.get(pk=self.id)
            if topic.title != self.title:
                self.slug = self.create_topic_slug(title_slug)
        else:
            self.slug = self.create_topic_slug(title_slug)

        super(Topic, self).save(*args, **kwargs)


class History(models.Model):
    topic = models.ForeignKey(Topic)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __unicode__(self):
        return self.title

    def create_slug(self, title_slug):
        slugcount = 0
        while True:
            try:
                History.objects.get(slug=title_slug)
                slugcount = slugcount + 1
                title_slug = title_slug + '-' + str(slugcount)
            except ObjectDoesNotExist:
                return title_slug

books/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from books.models import Book, Topic, PRIVACY_CHOICES, History
from books.forms import BookForm, TopicForm
from django.core.exceptions import ObjectDoesNotExist
from micro_admin.models import User
from django.db.models import Q
import json
import datetime


@login_required
def books(request):
    books = Book.objects.all().order_by('created_on')
    return render(request, "docs/books/list_of_books.html", {"books": books})


@login_required
def create_book(request):
    if request.user.is_superuser:
        if request.method == "POST":
            book_form = BookForm(request.POST)

            if book_form.is_valid():
                book = book_form.save()
                book.status = request.POST.get('status') if request.POST.get('status') else 'Waiting'
                book.display_order = Book.objects.all().count()
                book.authors.add(request.user)
                book.save()
                data = {"error": False, "response": "Book created"}

            else:
                data = {"error": True, "response": book_form.errors}

            return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')

        users = User.objects.all()
        return render(request, "docs/books/create_book.html", {"users": users, "privacy_choices": PRIVACY_CHOICES})

    return render_to_response("admin/accessdenied.html")


@login_required
def view_book(request, slug):
    book = get_object_or_404(Book, slug=slug)
    return render(request, "docs/books/book_detail.html", {"book": book})


@login_required
def view_book_topics(request, slug):
    book = get_object_or_404(Book, slug=slug)
    topics = Topic.objects.filter(book=book, parent__isnull=True, shadow__isnull=True)
    return render(request, "docs/topics/list_of_book_topics.html", {"book": book, "topics": topics})


@login_required
def create_topic(request, slug):
    book = get_object_or_404(Book, slug=slug)
    if request.method == "POST":
        topic_form = TopicForm(request.POST)
        
        if topic_form.is_valid():
            topic = topic_form.save()
            topic.status = "Waiting"
            topic.authors.add(request.user)
            
            if request.user not in book.authors.all():
                book.authors.add(request.user)

            if request.POST.get("parent"):
                topic.parent = Topic.objects.get(id=request.POST.get("parent"))

            topic.display_order = Topic.objects.filter(book=book,
                                    parent=topic.parent, shadow__isnull=True).count()
            topic.save()

            data = {"error": False, "response": "Topic created"}
        else:
            data = {"error": True, "response": topic_form.errors}
        
        return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')
    topics = Topic.objects.filter(book=book.id, parent__isnull=True, shadow__isnull=True)    
    return render(request, "docs/topics/create_topic.html", {"book": book, "topics":topics})


@login_required
def create_content(request, book_slug, topic_slug):
    topic = get_object_or_404(Topic, slug=topic_slug)
    book = get_object_or_404(Book, slug=book_slug)
    if request.method == "POST" and request.POST.get("content"):
        if not topic.content:
            topic.content = request.POST.get("content")
            topic.keywords = request.POST.get("keywords")
            topic.updated_on = datetime.datetime.now()
            topic.save()
        else:
            topic_form = TopicForm(request.POST)
        
            if topic_form.is_valid():
                new_topic = topic_form.save()
                new_topic.status = "Waiting"
                new_topic.keywords = request.POST.get("keywords")
                new_topic.authors.add(request.user)

                if request.user not in book.authors.all():
                    book.authors.add(request.user)
                    
                if request.POST.get('parent'):
                    topic_inst = Topic.objects.get(id=request.POST.get('parent'))
                    new_topic.parent = topic_inst

                new_topic.shadow = topic
                new_topic.content = request.POST.get("content")
                new_topic.display_order = Topic.objects.filter(book__slug=book_slug,
                        parent=new_topic.parent, shadow=new_topic.shadow).count()

                new_topic.save()

        if request.user not in topic.authors.all():
            topic.authors.add(request.user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def view_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    topic = get_object_or_404(Topic, slug=topic_slug)
    topic_shadows = Topic.objects.filter(shadow=topic.id)
    return render(request, "docs/topics/topic_detail.html", {"book": book, "topic": topic, "topic_shadows": topic_shadows})


@login_required
def view_subtopic(request, book_slug, topic_slug, subtopic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    topic = get_object_or_404(Topic, slug=topic_slug)
    subtopic = get_object_or_404(Topic, slug=subtopic_slug)
    subtopic_shadows = Topic.objects.filter(shadow=subtopic.id)
    return render(request, "docs/topics/topic_detail.html", {"book": book, "topic": topic, "subtopic": subtopic, "subtopic_shadows": subtopic_shadows})


# @login_required
# def view_book_doc(request, slug):
#     book = Book.objects.get(slug=slug)
#     topics = Topic.objects.filter(book=book, parent__isnull=True, shadow__isnull=True)
#     return render(request, "docs/books/book_document.html", {"book": book, "topics": topics})


@login_required
def edit_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    topic = get_object_or_404(Topic, slug=topic_slug)

    if request.method == "POST":
        topic_form = TopicForm(request.POST)
        
        if topic_form.is_valid():
            new_topic = topic_form.save()
            new_topic.status = "Waiting"
            new_topic.authors.add(request.user)
            
            if request.user not in book.authors.all():
                book.authors.add(request.user)

            if request.user not in topic.authors.all():
                topic.authors.add(request.user)

            if request.POST.get('parent'):
                new_topic.parent = request.POST.get('parent')

            new_topic.shadow = topic

            new_topic.save()

            data = {"error": False, "response": "Topic has been edited Successfully"}
        else:
            data = {"error": True, "response": topic_form.errors}
        
        return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')
    topics = Topic.objects.filter(book=book.id, parent__isnull=True, shadow__isnull=True)    
    return render(request, "docs/topics/edit_topic.html", {"book": book, "topics":topics, "topic": topic})


@login_required
def approve_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    
    if request.user.is_superuser or book.admin == request.user:
        
        topic = get_object_or_404(Topic, slug=topic_slug)
        if topic.shadow:
            history = History.objects.create(topic=topic.shadow, title=topic.shadow.title, 
                            content=topic.shadow.content)

            history.slug = history.create_slug(topic.shadow.slug)
            history.save()

            topic.shadow.title = topic.title
            topic.shadow.status = "Approved"
            topic.shadow.content = topic.content
            topic.shadow.keywords = topic.keywords
            topic.shadow.updated_on = datetime.datetime.now()
            topic.shadow.save()

            topic.delete()
            data = {"topic_slug": topic.shadow.slug, "response": "Approved Successfully"}
        else:
            topic.status = "Approved"
            topic.save()
            data = {"response": "Approved Successfully"}
    else:
        data = {"response": "You don't have the permission to Approve."}
    return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')


@login_required
def reject_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    
    if request.user.is_superuser or book.admin == request.user:
        topic = get_object_or_404(Topic, slug=topic_slug)
        topic.status = "Rejected"
        topic.save()
        data = {"response": "Rejected Successfully"}
    else:
        data = {"response": "You don't have the permission to Reject."}
    return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')


@login_required
def delete_topic(request, book_slug, topic_slug):
    book = get_object_or_404(Book, slug=book_slug)
    
    if request.user.is_superuser or book.admin == request.user:
        topic = get_object_or_404(Topic, slug=topic_slug)
        topic_id = topic.id
        topic.delete()

        if not topic.shadow:
            remaining_topics = Topic.objects.filter(id__gte=topic_id, parent=topic.parent, shadow=topic.shadow)
            for each_topic in remaining_topics:
                each_topic.display_order = (each_topic.display_order) - 1
                each_topic.save()

        data = {"response": "Deleted Successfully"}
    else:
        data = {"response": "You don't have the permission to Delete."}
    return HttpResponse(json.dumps(data), content_type='application/json; charset=utf-8')


@login_required
def edit_book(request, slug):
    book = get_object_or_404(Book, slug=slug)
    if request.user.is_superuser or book.admin == request.user:

        if request.method == "POST":

templates/docs/book_topics.html
{% load user_tags %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% if topic %}{{ topic.title }} | {% elif subtopic %}{{ subtopic.title }} | {{ subtopic.parent.title }} | {% endif %}{{book.title}} | Micro Pyramid</title>
    <meta name="description" content="{% if topic %}{{ topic.title }} - {{ book.title }} - Books{% elif subtopic %}{{ subtopic.title }} - {{ subtopic.parent.title }} - {{ book.title }} - Books{% else %}{{ book.title }} - Books{% endif %} - MicroPyramid." />
    <meta name="keywords" content="{% if topic %}{{ topic.keywords }}{% elif subtopic %}{{ subtopic.keywords }}{% else %}{{ book.keywords }}{% endif %}" />
    <link rel="shortcut icon" href="/static/favicon.png">
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    {% load compress %}
    {% compress css %}
    <link rel="stylesheet" href="/static/site/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/site/less/theme_extra.less" type="text/less">
    <link rel="stylesheet" type="text/less" href="/static/site/less/bs_leftnavi.less">
    <link rel="stylesheet" type="text/less" href="/static/site/less/books.less">
    {% endcompress %}

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    {% compress js %}
    <script src="/static/site/js/bootstrap.js" defer></script>
    <script src="/static/site/js/modernizr.custom.js" defer></script>
    <script src="/static/site/js/theme.js" defer></script>
    <script src="/static/site/js/bs_leftnavi.js" defer></script>
    {% endcompress %}
  </head>
  <body class="docs-body" role="document" data-twttr-rendered="true">
    <div class="docs-main-nav">
      <nav data-toggle="wy-nav-shift" class="left-side-nav stickynav">
        <div>
          <div class="left-search-title">
            <div class="title"><a href="{% url "books:book_info" slug=book.slug %}">{{book.title}}</a></div>
            <!-- <div class="search-bar"><input type="text" class="form-control" placeholder="search your document"></div> -->
          </div>
          <div class="nano-content">
            <ul class="gw-nav gw-nav-list">
              {% for topic in parent_topics %}
                {% with topic.topic_set.all as subtopics %}
                  <li class="{% if subtopics %}init-arrow-down{%else%}init-un-active{% endif %}">
                    <a href="{% url "books:topic_info" topic_slug=topic.slug book_slug=book.slug %}">
                      <span class="gw-menu-text">{{topic.title}}</span>
                    </a>
                    {% if subtopics %}
                      <b class="gw-arrow"></b>
                      <ul class="gw-submenu">
                        {% for subtopic in subtopics %}
                          {% if subtopic.status == "Approved" and not subtopic.shadow %}
                            <li>
                              <a href="{% url "books:subtopic_info" topic_slug=topic.slug subtopic_slug=subtopic.slug book_slug=book.slug %}">{{subtopic.title}}</a>
                            </li>
                          {% endif %}
                        {% endfor %}
                      </ul> 
                    {% endif %}
                  </li>
                {% endwith %}
              {% endfor %}
            </ul>
          </div>
        </div>
        &nbsp;
      </nav>
      <section data-toggle="wy-nav-shift" class="docs-content">
        <nav class="mobile-nav-top" role="navigation" aria-label="top navigation">
          <i data-toggle="mobile-nav-top" class="fa fa-bars"></i>
          <a href="#">{{book.title}}</a>
        </nav>
        <div class="right-doc-content">
          {% if topic %}
            <h3>{{topic.title}}</h3>
          {% elif subtopic %}
            <h3>{{subtopic.title}}</h3>
          {% else %}
            <h3>{{book.title}}</h3>
          {% endif %}

          {% if topic %}
            {{topic.content|convert_to_html|safe}}
          {% elif subtopic %}
            {{subtopic.content|convert_to_html|safe}}
          {% else %}
            {{book.description|convert_to_html|safe}}
          {% endif %}
        </div>
      </section>
    </div>
    {% compress js %}
    <script type="text/javascript">
      $(document).ready(function() {
        var list_item = $('a[href="'+window.location.pathname+'"]').parent("li")
        list_item.addClass("active");
        if (list_item.hasClass("init-arrow-down") || list_item.hasClass("arrow-down")){
          list_item.attr("class", "arrow-down active");
          list_item.children('ul').show();
        }
        else{
          list_item.parent('ul').show();
          list_item.parent('ul').parent('li').attr("class", "arrow-down")
        }
      });
    </script>
    {% endcompress %}
  </body>
</html>

templates/docs/books.html
{% extends 'site/base.html' %}
{% load compress %}
{% load user_tags %}

{% block title %} Docs | MicroPyramid {% endblock %}
{% block extra-styles %}
  {% compress css %}
    <link href="/static/site/less/books.less" rel="stylesheet" type="text/less">
  {% endcompress %}
{% endblock %}

{% block stage %}
  <!-- <div class="row marl isotope-row">
      <div class="container">
        <div class="portfolioFilter">
          <a href="#" data-filter="*" class="current active">All Categories</a>
          <a href="#" data-filter=".people">People</a>
          <a href="#" data-filter=".places">Places</a>
          <a href="#" data-filter=".food">Food</a>
          <a href="#" data-filter=".objects">Objects</a>
        </div>
      </div>
    </div> -->

    <!-- Books starts here -->
    <div class="row marl books-row">
      <div class="container">
        <div class="row marl">
          <div class="portfolioContainer">
            {% if books %}
              {% for book in books %}
                <!-- book item starts here -->
                <div class="col-md-3 col-sm-4 col-xs-12 book-block">
                  <div class="book-item">
                    
                    <div class="book-title pink-red">
                      {% ifequal book.privacy 'Private'%} 
                        <div class="book-privacy-flap"> {{book.privacy}} </div>
                      {% endifequal %}
                      <a href="{% url "books:book_info" slug=book.slug %}">{{book.title}}</a>
                    </div>
                    <div class="book-description">
                      {{book.description|convert_to_html|safe}}
                    </div>
                    <div class="date-time">
                      <i class="fa fa-clock-o"></i> Last Updated on {{book.updated_on|date:"b d, Y"}}
                    </div>
                  </div>
                </div>
                <!-- book item ends here -->
              {% endfor %}
            {% else %}
              <span>No books available</span>
            {% endif %}
          </div>
      </div>
    </div>
    <!-- Books ends here -->
{% endblock %}
{% block footer %}
{% endblock %}